phrase:
  project_id: 15d32bafd4ffe92f156bcca0549a07e6
  file_format: xml
  push:
    sources:
    ignore:
      - '**/values-es-rUS/**'
      - '**/values-fr-rCA/**'
  pull:
    targets:
      - file: ./instashopper-android/shared/**/content/es-rUS/strings.xml
        params:
          locale_id: es-rUS
          file_format: xml
      - file: ./instashopper-android/shared/**/content/fr-rCA/strings.xml
        params:
          locale_id: fr-rCA
          file_format: xml
