phrase:
  project_id: 15d32bafd4ffe92f156bcca0549a07e6

  push:
    sources:
      - file: ./source-locale/main/json-files/**/*.json
        exclude:
          - '**/*/*[a-z]{2}-[a-z]{2}/*'  # Exclude any folders with locale codes (e.g., 'cs-cz', 'en-us')
          - '**/*/*[a-z]{2}/*'  # Exclude any folders with 2-letter locale codes (e.g., 'cs', 'en')
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true

  pull:
    targets:
      - file: ./translation-files/de/<basename>.json
        params:
          locale_id: es-US
          file_format: simple_json

      - file: ./translation-files/es/<basename>.json
        params:
          locale_id: fr-CA
          file_format: simple_json
