phrase:
  project_id: 15d32bafd4ffe92f156bcca0549a07e6
  file_format: xml
  push:
    sources:
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_1

    - file: ./instashopper-android/shared/shopper-automate-batch-trigger/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_2

    - file: ./instashopper-android/shared/ids-compose/public/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_3

    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_4

    - file: ./instashopper-android/shared/shopper-audit/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_5

    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_6

    - file: ./instashopper-android/shared/shopper-app-health/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_7

    - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_8

    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_9

    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_10

    - file: ./instashopper-android/shared/shopper-auth-passkey/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_11

    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_12

    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_13

    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_14

  pull:
      targets:
      - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_1
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-automate-batch-trigger/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_2
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/ids-compose/public/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_3
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_4
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-audit/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_5
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_6
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-app-health/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_7
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_8
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_9
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_10
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-auth-passkey/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_11
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_12
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_13
          exclude_locales:
            - en
      - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-<android_code>/strings.xml
        params:
          file_format: xml
          tags: folder_14
          exclude_locales:
            - en
