phrase:
  project_id: 15d32bafd4ffe92f156bcca0549a07e6
  file_format: xml
  
  push:
    sources:
      - file: ./**/*.xml  # Match all .json files in nested folders
        exclude:
          - '**/*/*[a-z]{2}-[a-z]{2}/*'  # Exclude any folders with locale codes (e.g., 'cs-cz', 'en-us')
          - '**/*/*[a-z]{2}/*'  # Exclude any folders with 2-letter locale codes (e.g., 'cs', 'en')
        params:
          file_format: xml
          locale_id: en
          update_translations: true
          tags: "{{ folder_name }}"  # Use the folder name as the tag (handled by an external process or script)
  
  pull:
    targets:
      - file: ./**/values-<locale_code>/strings.xml  # Match all target .json files in nested folders based on locale code
        params:
          file_format: xml
          tags: "{{ folder_name }}"  # Use the folder name as the tag (handled by an external process or script)
