phrase:
  project_id: 15d32bafd4ffe92f156bcca0549a07e6

  push:
    sources:
      - file: ./**/*.xml
        exclude:
          - '**/*/*[a-z]{2}-[a-z]{2}/*'  # Exclude any folders with locale codes (e.g., 'cs-cz', 'en-us')
          - '**/*/*[a-z]{2}/*'  # Exclude any folders with 2-letter locale codes (e.g., 'cs', 'en')
        params:
          file_format: xml
          locale_id: en
          update_translations: true

  pull:
    targets:
      - file: ./translation-files/<locale_code>/string.xml
        params:
          locale_id: es-US
          file_format: xml

      - file: ./translation-files/<locale_code>/string.xml
        params:
          locale_id: fr-CA
          file_format: xml
