phrase:
  project_id: 61b49556733b0ed52699587486214940

  push:
    sources:
      - file: ./source-locale/main/json-files/**/*.json
        excludes:
          - "**/fr*/**"
          - "**/es*/**"
          - "**/de*/**"
          - "**/ja*/**"
          - "**/zh*/**"
          - "**/el*/**"
        params:
          file_format: simple_json
          locale_id: en
          update_translations: true

  pull:
    targets:
      - file: ./translation-files/de/<basename>.json
        params:
          locale_id: de
          file_format: simple_json

      - file: ./translation-files/es/<basename>.json
        params:
          locale_id: es
          file_format: simple_json

      - file: ./translation-files/el/<basename>.json
        params:
          locale_id: el
          file_format: simple_json

      - file: ./source-locale/main/json-files/<basename>.json
        params:
          locale_id: en
          file_format: simple_json
