phrase:
  project_id: 15d32bafd4ffe92f156bcca0549a07e6
  file_format: xml
  push:
    sources:
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_1
        unique_id: folder_1
    - file: ./instashopper-android/shared/shopper-automate-batch-trigger/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_2
        unique_id: folder_2
    - file: ./instashopper-android/shared/ids-compose/public/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_3
        unique_id: folder_3
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_4
        unique_id: folder_4
    - file: ./instashopper-android/shared/shopper-audit/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_5
        unique_id: folder_5
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_6
        unique_id: folder_6
    - file: ./instashopper-android/shared/shopper-app-health/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_7
        unique_id: folder_7
    - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_8
        unique_id: folder_8
    - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values-fr-CA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_9
        unique_id: folder_9
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_10
        unique_id: folder_10
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_11
        unique_id: folder_11
    - file: ./instashopper-android/shared/shopper-auth-passkey/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_12
        unique_id: folder_12
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_13
        unique_id: folder_13
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_14
        unique_id: folder_14
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_15
        unique_id: folder_15
  pull:
    targets:
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_1
        unique_id: folder_1
    - file: ./instashopper-android/shared/shopper-automate-batch-trigger/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_2
        unique_id: folder_2
    - file: ./instashopper-android/shared/ids-compose/public/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_3
        unique_id: folder_3
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_4
        unique_id: folder_4
    - file: ./instashopper-android/shared/shopper-audit/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_5
        unique_id: folder_5
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_6
        unique_id: folder_6
    - file: ./instashopper-android/shared/shopper-app-health/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_7
        unique_id: folder_7
    - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_8
        unique_id: folder_8
    - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values-fr-CA-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_9
        unique_id: folder_9
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_10
        unique_id: folder_10
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_11
        unique_id: folder_11
    - file: ./instashopper-android/shared/shopper-auth-passkey/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_12
        unique_id: folder_12
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_13
        unique_id: folder_13
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_14
        unique_id: folder_14
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_15
        unique_id: folder_15
