phrase:
  project_id: 15d32bafd4ffe92f156bcca0549a07e6
  file_format: xml
  push:
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 1
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 2
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 3
    - file: ./instashopper-android/shared/shopper-automate-batch-trigger/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 4
    - file: ./instashopper-android/shared/shopper-automate-batch-trigger/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 5
    - file: ./instashopper-android/shared/shopper-automate-batch-trigger/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 6
    - file: ./instashopper-android/shared/ids-compose/public/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 7
    - file: ./instashopper-android/shared/ids-compose/public/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 8
    - file: ./instashopper-android/shared/ids-compose/public/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 9
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 10
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 11
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 12
    - file: ./instashopper-android/shared/shopper-audit/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 13
    - file: ./instashopper-android/shared/shopper-audit/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 14
    - file: ./instashopper-android/shared/shopper-audit/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 15
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 16
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 17
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 18
    - file: ./instashopper-android/shared/shopper-app-health/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 19
    - file: ./instashopper-android/shared/shopper-app-health/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 20
    - file: ./instashopper-android/shared/shopper-app-health/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 21
    - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 22
    - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 23
    - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 24
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 25
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 26
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 27
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 28
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 29
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 30
    - file: ./instashopper-android/shared/shopper-auth-passkey/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 31
    - file: ./instashopper-android/shared/shopper-auth-passkey/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 32
    - file: ./instashopper-android/shared/shopper-auth-passkey/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 33
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 34
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 35
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 36
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 37
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 38
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 39
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values - 40
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-es-rUS/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-es-rUS - 41
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-fr-rCA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: main
        unique_id: main/values-fr-rCA - 42
