phrase:
  project_id: 15d32bafd4ffe92f156bcca0549a07e6
  file_format: xml
  push:
    - file: ./instashopper-android/shared/**/*.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: shared
