phrase:
  project_id: 15d32bafd4ffe92f156bcca0549a07e6
  file_format: xml
  push:
    sources:
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values-es-US/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_1
        unique_id: folder_1
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_2
        unique_id: folder_2
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values-fr-CA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_3
        unique_id: folder_3
    - file: ./instashopper-android/shared/shopper-automate-batch-trigger/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_4
        unique_id: folder_4
    - file: ./instashopper-android/shared/ids-compose/public/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_5
        unique_id: folder_5
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-es-US/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_6
        unique_id: folder_6
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_7
        unique_id: folder_7
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-en/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_8
        unique_id: folder_8
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-fr-CA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_9
        unique_id: folder_9
    - file: ./instashopper-android/shared/shopper-audit/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_10
        unique_id: folder_10
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-es-US/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_11
        unique_id: folder_11
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_12
        unique_id: folder_12
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-en/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_13
        unique_id: folder_13
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-fr-CA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_14
        unique_id: folder_14
    - file: ./instashopper-android/shared/shopper-app-health/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_15
        unique_id: folder_15
    - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_16
        unique_id: folder_16
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-es-US/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_17
        unique_id: folder_17
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_18
        unique_id: folder_18
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-en/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_19
        unique_id: folder_19
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-fr-CA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_20
        unique_id: folder_20
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-es-US/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_21
        unique_id: folder_21
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_22
        unique_id: folder_22
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-en/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_23
        unique_id: folder_23
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-fr-CA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_24
        unique_id: folder_24
    - file: ./instashopper-android/shared/shopper-auth-passkey/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_25
        unique_id: folder_25
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-es-US/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_26
        unique_id: folder_26
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_27
        unique_id: folder_27
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-en/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_28
        unique_id: folder_28
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-fr-CA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_29
        unique_id: folder_29
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-es-US/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_30
        unique_id: folder_30
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_31
        unique_id: folder_31
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-en/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_32
        unique_id: folder_32
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-fr-CA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_33
        unique_id: folder_33
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-es-US/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_34
        unique_id: folder_34
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_35
        unique_id: folder_35
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-en/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_36
        unique_id: folder_36
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-fr-CA/strings.xml
      params:
        file_format: xml
        locale_id: en
        update_translations: true
        tags: folder_37
        unique_id: folder_37
  pull:
      targets:
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values-es-US-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_1
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_2
    - file: ./instashopper-android/shared/shopper-automate-cycle-counts/impl/src/main/res/values-fr-CA-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_3
    - file: ./instashopper-android/shared/shopper-automate-batch-trigger/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_4
    - file: ./instashopper-android/shared/ids-compose/public/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_5
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-es-US-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_6
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_7
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-en-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_8
    - file: ./instashopper-android/shared/shopper-automate-locate/impl/src/main/res/values-fr-CA-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_9
    - file: ./instashopper-android/shared/shopper-audit/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_10
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-es-US-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_11
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_12
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-en-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_13
    - file: ./instashopper-android/shared/shopper-automate-scan/impl/src/main/res/values-fr-CA-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_14
    - file: ./instashopper-android/shared/shopper-app-health/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_15
    - file: ./instashopper-android/shared/shopper-achievement-celebration/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_16
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-es-US-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_17
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_18
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-en-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_19
    - file: ./instashopper-android/shared/shopper-automate-scan-simulator/impl/src/main/res/values-fr-CA-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_20
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-es-US-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_21
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_22
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-en-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_23
    - file: ./instashopper-android/shared/shopper-automate-item-scan/impl/src/main/res/values-fr-CA-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_24
    - file: ./instashopper-android/shared/shopper-auth-passkey/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_25
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-es-US-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_26
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_27
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-en-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_28
    - file: ./instashopper-android/shared/shopper-automate-picking/impl/src/main/res/values-fr-CA-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_29
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-es-US-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_30
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_31
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-en-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_32
    - file: ./instashopper-android/shared/shopper-automate-stow-help/impl/src/main/res/values-fr-CA-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_33
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-es-US-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_34
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_35
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-en-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_36
    - file: ./instashopper-android/shared/shopper-automate-staging/impl/src/main/res/values-fr-CA-<android_code>/strings.xml
      params:
        file_format: xml
        locale_id: <locale_code>
        tags: folder_37
